version: '3'
services:
  nest: 
    image: nest-api:latest
    restart: always
    ports:
      - "3001:3000"
    container_name: nest
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: e-commerce
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  pgdata:
